import type { Book } from '@/lib/types';

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    coverUrl: 'https://placehold.co/300x450.png',
    description: 'A novel about the American dream.',
    formats: ['Audiobook', 'eBook', 'Print'],
    sources: [
      { name: 'Libby', availability: 'Available', url: '#' },
      { name: 'Hoopla', availability: 'Unavailable', url: '#' },
      { name: 'PDF', availability: 'Check', url: '#' },
      { name: 'Amazon Used', price: '$4.99', availability: 'Available', url: '#' },
      { name: 'Amazon New', price: '$12.99', availability: 'Available', url: '#' },
    ],
  },
  {
    id: '2',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    coverUrl: 'https://placehold.co/300x450.png',
    description: 'A novel about injustice in the American South.',
    formats: ['eBook', 'Print'],
    sources: [
      { name: 'Libby', availability: 'Unavailable', url: '#' },
      { name: 'Hoopla', availability: 'Available', url: '#' },
      { name: 'PDF', availability: 'Check', url: '#' },
      { name: 'Amazon Used', price: '$6.50', availability: 'Available', url: '#' },
      { name: 'Amazon New', price: '$14.00', availability: 'Available', url: '#' },
    ],
  },
  {
    id: '3',
    title: '1984',
    author: 'George Orwell',
    coverUrl: 'https://placehold.co/300x450.png',
    description: 'A dystopian novel about totalitarianism.',
    formats: ['Audiobook', 'Print'],
    sources: [
      { name: 'Libby', availability: 'Available', url: '#' },
      { name: 'Hoopla', availability: 'Available', url: '#' },
      { name: 'PDF', availability: 'Check', url: '#' },
      { name: 'Amazon Used', price: '$5.25', availability: 'Available', url: '#' },
      { name: 'Amazon New', price: '$11.75', availability: 'Available', url: '#' },
    ],
  },
   {
    id: '4',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    coverUrl: 'https://placehold.co/300x450.png',
    description: 'A romantic novel of manners.',
    formats: ['Audiobook', 'eBook', 'Print'],
    sources: [
      { name: 'Libby', availability: 'Available', url: '#' },
      { name: 'Hoopla', availability: 'Available', url: '#' },
      { name: 'PDF', availability: 'Check', url: '#' },
      { name: 'Amazon Used', price: '$3.99', availability: 'Available', url: '#' },
      { name: 'Amazon New', price: '$10.99', availability: 'Available', url: '#' },
    ],
  },
   {
    id: '5',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    coverUrl: 'https://placehold.co/300x450.png',
    description: 'A fantasy novel and prelude to The Lord of the Rings.',
    formats: ['Audiobook', 'eBook', 'Print'],
    sources: [
      { name: 'Libby', availability: 'Unavailable', url: '#' },
      { name: 'Hoopla', availability: 'Available', url: '#' },
      { name: 'PDF', availability: 'Check', url: '#' },
      { name: 'Amazon Used', price: '$7.00', availability: 'Available', url: '#' },
      { name: 'Amazon New', price: '$15.00', availability: 'Available', url: '#' },
    ],
  },
   {
    id: '6',
    title: 'Dune',
    author: 'Frank Herbert',
    coverUrl: 'https://placehold.co/300x450.png',
    description: 'A science fiction epic set in the distant future.',
    formats: ['Audiobook', 'eBook', 'Print'],
    sources: [
      { name: 'Libby', availability: 'Available', url: '#' },
      { name: 'Hoopla', availability: 'Unavailable', url: '#' },
      { name: 'PDF', availability: 'Check', url: '#' },
      { name: 'Amazon Used', price: '$8.50', availability: 'Available', url: '#' },
      { name: 'Amazon New', price: '$17.99', availability: 'Available', url: '#' },
    ],
  },
];
