import type { Book } from '@/lib/types';

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    coverUrl: 'https://placehold.co/300x450.png',
    description: 'A novel about the American dream.',
    formats: ['Audiobook', 'eBook', 'Print'],
    sources: [
      { name: 'Libby', availability: 'Available', url: `https://www.google.com/search?q=site%3Alibbyapp.com+${encodeURIComponent('The Great Gatsby')}` },
      { name: 'Hoopla', availability: 'Unavailable', url: `https://www.hoopladigital.com/search?q=${encodeURIComponent('The Great Gatsby')}` },
      { name: 'PDF', availability: 'Check', url: `https://www.google.com/search?q=${encodeURIComponent('The Great Gatsby')}+filetype%3Apdf` },
      { name: 'Amazon Used', price: '$4.99', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent('The Great Gatsby')}` },
      { name: 'Amazon New', price: '$12.99', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent('The Great Gatsby')}` },
    ],
  },
  {
    id: '2',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    coverUrl: 'https://placehold.co/300x450.png',
    description: 'A novel about injustice in the American South.',
    formats: ['eBook', 'Print'],
    sources: [
      { name: 'Libby', availability: 'Unavailable', url: `https://www.google.com/search?q=site%3Alibbyapp.com+${encodeURIComponent('To Kill a Mockingbird')}` },
      { name: 'Hoopla', availability: 'Available', url: `https://www.hoopladigital.com/search?q=${encodeURIComponent('To Kill a Mockingbird')}` },
      { name: 'PDF', availability: 'Check', url: `https://www.google.com/search?q=${encodeURIComponent('To Kill a Mockingbird')}+filetype%3Apdf` },
      { name: 'Amazon Used', price: '$6.50', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent('To Kill a Mockingbird')}` },
      { name: 'Amazon New', price: '$14.00', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent('To Kill a Mockingbird')}` },
    ],
  },
  {
    id: '3',
    title: '1984',
    author: 'George Orwell',
    coverUrl: 'https://placehold.co/300x450.png',
    description: 'A dystopian novel about totalitarianism.',
    formats: ['Audiobook', 'Print'],
    sources: [
      { name: 'Libby', availability: 'Available', url: `https://www.google.com/search?q=site%3Alibbyapp.com+${encodeURIComponent('1984')}` },
      { name: 'Hoopla', availability: 'Available', url: `https://www.hoopladigital.com/search?q=${encodeURIComponent('1984')}` },
      { name: 'PDF', availability: 'Check', url: `https://www.google.com/search?q=${encodeURIComponent('1984')}+filetype%3Apdf` },
      { name: 'Amazon Used', price: '$5.25', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent('1984')}` },
      { name: 'Amazon New', price: '$11.75', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent('1984')}` },
    ],
  },
   {
    id: '4',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    coverUrl: 'https://placehold.co/300x450.png',
    description: 'A romantic novel of manners.',
    formats: ['Audiobook', 'eBook', 'Print'],
    sources: [
      { name: 'Libby', availability: 'Available', url: `https://www.google.com/search?q=site%3Alibbyapp.com+${encodeURIComponent('Pride and Prejudice')}` },
      { name: 'Hoopla', availability: 'Available', url: `https://www.hoopladigital.com/search?q=${encodeURIComponent('Pride and Prejudice')}` },
      { name: 'PDF', availability: 'Check', url: `https://www.google.com/search?q=${encodeURIComponent('Pride and Prejudice')}+filetype%3Apdf` },
      { name: 'Amazon Used', price: '$3.99', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent('Pride and Prejudice')}` },
      { name: 'Amazon New', price: '$10.99', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent('Pride and Prejudice')}` },
    ],
  },
   {
    id: '5',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    coverUrl: 'https://placehold.co/300x450.png',
    description: 'A fantasy novel and prelude to The Lord of the Rings.',
    formats: ['Audiobook', 'eBook', 'Print'],
    sources: [
      { name: 'Libby', availability: 'Unavailable', url: `https://www.google.com/search?q=site%3Alibbyapp.com+${encodeURIComponent('The Hobbit')}` },
      { name: 'Hoopla', availability: 'Available', url: `https://www.hoopladigital.com/search?q=${encodeURIComponent('The Hobbit')}` },
      { name: 'PDF', availability: 'Check', url: `https://www.google.com/search?q=${encodeURIComponent('The Hobbit')}+filetype%3Apdf` },
      { name: 'Amazon Used', price: '$7.00', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent('The Hobbit')}` },
      { name: 'Amazon New', price: '$15.00', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent('The Hobbit')}` },
    ],
  },
   {
    id: '6',
    title: 'Dune',
    author: 'Frank Herbert',
    coverUrl: 'https://placehold.co/300x450.png',
    description: 'A science fiction epic set in the distant future.',
    formats: ['Audiobook', 'eBook', 'Print'],
    sources: [
      { name: 'Libby', availability: 'Available', url: `https://www.google.com/search?q=site%3Alibbyapp.com+${encodeURIComponent('Dune')}` },
      { name: 'Hoopla', availability: 'Unavailable', url: `https://www.hoopladigital.com/search?q=${encodeURIComponent('Dune')}` },
      { name: 'PDF', availability: 'Check', url: `https://www.google.com/search?q=${encodeURIComponent('Dune')}+filetype%3Apdf` },
      { name: 'Amazon Used', price: '$8.50', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent('Dune')}` },
      { name: 'Amazon New', price: '$17.99', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent('Dune')}` },
    ],
  },
  {
    id: '7',
    title: "Analytics the Right Way: A Business Leader's Guide to Putting Data to Productive Use",
    author: 'Dr. Kirk Materne',
    coverUrl: 'https://placehold.co/300x450.png',
    description: "A business leader's guide to putting data to productive use.",
    formats: ['eBook', 'Print'],
    sources: [
      { name: 'Libby', availability: 'Available', url: `https://www.google.com/search?q=site%3Alibbyapp.com+${encodeURIComponent("Analytics the Right Way")}` },
      { name: 'Hoopla', availability: 'Unavailable', url: `https://www.hoopladigital.com/search?q=${encodeURIComponent("Analytics the Right Way")}` },
      { name: 'PDF', availability: 'Check', url: `https://www.google.com/search?q=${encodeURIComponent("Analytics the Right Way")}+filetype%3Apdf` },
      { name: 'Amazon Used', price: '$15.50', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent("Analytics the Right Way")}` },
      { name: 'Amazon New', price: '$25.99', availability: 'Available', url: `https://www.amazon.com/s?k=${encodeURIComponent("Analytics the Right Way")}` },
    ],
  },
];
